spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

cors:
  allowed-origins:
    - "http://localhost:3000"

logging:
  level:
    org.hibernate.SQL: debug