spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

cors:
  allowed-origins:
    - "http://192.168.56.111"

logging:
  level:
    org.hibernate.SQL: error