spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

cors:
  allowed-origins:
    - "http://localhost:3000"

discord:
  webhook:
    url: ${DISCORD_WEBHOOK_URL:none}